### ISSUE TITLE
Next App directory support

### ISSUE THREAD

**Issue by perevezencev** [fabian-hiller/modular-forms#164]
Hi everyone, I am getting this error when I use AppRouter with nextjs
```
 X node_modules/@preact/signals-react/dist/signals.mjs (1:3269) @ eval
 X TypeError: Cannot set property jsx of [object Module] which has only a getter
    at __webpack_require__ (/home/projects/stackblitz-starters-9ktj3u/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/home/projects/stackblitz-starters-9ktj3u/.next/server/webpack-runtime.js:33:42)
    at eval (./app/page.tsx:7:78)
    at (ssr)/./app/page.tsx (/home/projects/stackblitz-starters-9ktj3u/.next/server/app/page.js:151:1)
    at __webpack_require__ (/home/projects/stackblitz-starters-9ktj3u/.next/server/webpack-runtime.js:33:42)
null
```
https://stackblitz.com/edit/stackblitz-starters-9ktj3u?file=app%2Fproducts%2Fcreation%2Fpage.tsx

**Comment by fabian-hiller** [comment]
Sadly Modular Forms is currently not compatible with Next.js: https://modularforms.dev/react/guides/installation

**Comment by perevezencev** [comment]
My bad! Thanks for answer
