### ISSUE TITLE
valiForm error

### ISSUE THREAD

**Issue by robodna** [fabian-hiller/modular-forms#220]
SOLVED:

I have created a valibot validation schema and use it to pass as a 'validate' option to createForm.  When I submit the form, I get the following error:

`valiForm.js?v=6f089068:10 Uncaught (in promise) TypeError: schema._parse is not a function
    at Object.validate (valiForm.js?v=6f089068:10:37)
    at handleFormOk (generic-view-edit.tsx:195:43)
    at Object.onOkClick (generic-view-edit.tsx:268:46)
    at _el$8.$$click (form-ok-cancel-bar.tsx:54:168)
    at HTMLDocument.eventHandler (chunk-QGXPAKYS.js?v=6f089068:829:63)`

The valibot schema does work when I call it directly using safeParse and manual data, however it throws the error when I attach the same schema to the 'validate' option of createForm.

Any ideas on what I may be doing wrong, or is this a bug?

UPDATE:  I upgraded modular-form from version .20 to .21 and everything works as expected now.

Thank you,

**Comment by fabian-hiller** [comment]
Thank you for the update!
