### ISSUE TITLE
Unable to build Qwik City app

### ISSUE THREAD

**Issue by lampask** [fabian-hiller/modular-forms#236]
## Problem

After installing `@modular-forms/qwik` package I am unable to build the application. There is import resolution error of "`valibot`" package. Is this package a neccesary dependency? I am not using valibot anywhere.

```
error during build:
[vite]: Rollup failed to resolve import "valibot" from "/home/projects/github-hatkqb/node_modules/.pnpm/@modular-forms+qwik@0.26.1_@builder.io+qwik-city@1.7.3_@builder.io+qwik@1.7.3_typescript@5.4.5/node_modules/@modular-forms/qwik/dist/s_b4myjhrwmxe.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/projects/github-hatkqb/node_modules/.pnpm/vite@5.3.5_@types+node@20.14.14/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65314:17)
    at onwarn (file:///home/projects/github-hatkqb/node_modules/.pnpm/@builder.io+qwik@1.7.3_@types+node@20.14.14/node_modules/@builder.io/qwik/dist/optimizer.mjs:6167:13)
    at onRollupWarning (file:///home/projects/github-hatkqb/node_modules/.pnpm/vite@5.3.5_@types+node@20.14.14/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65344:5)
    at onwarn (file:///home/projects/github-hatkqb/node_modules/.pnpm/vite@5.3.5_@types+node@20.14.14/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65009:7)
    at eval (file:///home/projects/github-hatkqb/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:18650:13)
    at Object.logger (file:///home/projects/github-hatkqb/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:20305:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/projects/github-hatkqb/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:19240:26)
    at eval (file:///home/projects/github-hatkqb/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:19198:26)
```

## Steps to reproduce
1. Create a new Qwik City starter project
2. Add @modular-forms/qwik as dev dependency
3. Try to build the project

**Comment by fabian-hiller** [comment]
Is this also the case if Modular Forms is a normal dependency. I think it should not be a dev dependency. Valibot should be installed automatically.

Unfortunately I had to add Valibot as a dependency. I will change and improve this in the future.

**Comment by lampask** [comment]
This problem indeed goes away when Modular Forms is loaded as normal dependency. Qwik utility functions advise to place it in the devDependencies, to avoid missing `qwik-city-plan`, but I guess Modular Forms bundles its own module.

I can get it to work also as a devDependency when I explicitely externalize valibot in `vite.config.ts`, extending the exported config like this:
```
build: {
  rollupOptions: {
    external: ["valibot"],
  },
},
```
