### ISSUE TITLE
formAction$ appears not to bundle correctly

### ISSUE THREAD

**Issue by imMadsen** [fabian-hiller/modular-forms#254]
Found this issue when trying to integrate drizzle using the following [guide](https://qwik.dev/docs/integrations/drizzle/).

The problem is when using the database connection within a formAction$ like in the following example

```
formAction$<LoginForm>(() => {
  const sql = postgres("postgresql://postgres:mysecretpassword@127.0.0.1:5432/cupon");
  const db = drizzle(sql);
}, valiForm$(LoginSchema));
```

One will get this error (Full log can be found [here](https://pastebin.com/U4CBTyuX)). It is my understanding from the [documentation ](https://qwik.dev/docs/integrations/modular-forms/)that formAction$ is executed on the server. Note that executing the same function within a server$, for an example will not lead to any issues. The error will also only occur when building the qwik app.

A temporary solution I've found is simply using the server$, and passing it as the function for the formAction$

```
file: C:/Users/root/Documents/GitHub/cupon-app/node_modules/postgres/src/connection.js:5:9
 
3: import crypto from 'crypto'
4: import Stream from 'stream'
5: import { performance } from 'perf_hooks'
            ^
6:
7: import { stringify, handleValue, arrayParser, arraySerializer } from './types.js'
 
    at getRollupError (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:14844:16)
    at Module.traceVariable (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:15291:29)
    at ModuleScope.findVariable (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:13192:39)
    at FunctionScope.findVariable (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionBodyScope.findVariable (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionScope.findVariable (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionBodyScope.findVariable (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at MemberExpression.bind (file:///C:/Users/root/Documents/GitHub/cupon-app/node_modules/rollup/dist/es/shared/node-entry.js:6860:49)
```

**Comment by fabian-hiller** [comment]
This is a known issue that I plan to address in the coming months. See [this issue](https://github.com/QwikDev/qwik/issues/5160). As a workaround, I recommend wrapping all of your `formAction$` code in `isServer`:

```ts
formAction$<LoginForm>(() => {
  if (isServer) {
    const sql = postgres("postgresql://postgres:mysecretpassword@127.0.0.1:5432/cupon");
    const db = drizzle(sql);
  }
}, valiForm$(LoginSchema));
```

**Comment by rafalfigura** [comment]
Hello, here is a repo with simple reproduction: https://github.com/rafalfigura/qwik-bundles-pg-in-client-dist
The method with isServer/isBrowser works as expected but still there is one warning with `node:async_hooks` like @svi3c pointed

**Comment by fabian-hiller** [comment]
I am very sorry about this problem. I still plan to submit a PR to Qwik and fix this. I hope to have time to do this by the end of the year.

**Comment by DustinJSilk** [comment]
Thanks for sharing solutions, this worked for me in the meantime:

```tsx
if (isBrowser) throw new Error('...')
```
